# sleek_cyber color theme for kitty
background            #16130b
foreground            #e9e2d4
selection_background  #4b4739
selection_foreground  #e9e2d4

cursor                #ddc66e
cursor_text_color     #16130b

# Black
color0  #16130b
color8  #4b4739
# Red
color1  #ffb4ab
color9  #ff897d
# Green
color2  #aad0b2
color10 #c6eccd
# Yellow / accent
color3  #ddc66e
color11 #fae287
# Blue
color4  #8fb497
color12 #aad0b2
# Magenta
color5  #d2c6a1
color13 #efe2bc
# Cyan
color6  #cdc6b4
color14 #e9e2d4
# White
color7  #cdc6b4
color15 #e9e2d4

# Window
background_opacity    0.88
blur_opacity          0.88
