# sleek_cyber — accent extracted from wallpaper
background        #16130b
foreground        #e9e2d4
cursor            #ddc66e
cursor_text_color #16130b

selection_background #ddc66e
selection_foreground #16130b

# Normal (0-7)
color0   #1a1714
color1   #ff5555
color2   #aad0b2
color3   #ddc66e
color4   #d2c6a1
color5   #c8956a
color6   #d2c6a1
color7   #e9e2d4

# Bright (8-15)
color8   #4b4739
color9   #ff7070
color10  #c5e6cc
color11  #ddc66e
color12  #d2c6a1
color13  #e0aa88
color14  #d2c6a1
color15  #ffffff

url_color #d2c6a1
