general {
    disable_loading_bar = true
    grace               = 3
    hide_cursor         = true
    no_fade_in          = false
}

background {
    monitor  =
    path     = ~/Pictures/Wallpapers/.current
    blur_size    = 7
    blur_passes  = 3
    brightness   = 0.7
    contrast     = 0.9
    vibrancy     = 0.2
}

input-field {
    monitor         =
    size            = 280, 50
    outline_thickness = 2
    dots_size       = 0.3
    dots_spacing    = 0.2
    dots_center     = true
    outer_color     = rgba(4b4739ff)
    inner_color     = rgba(16130bcc)
    font_color      = rgb(e9e2d4)
    fade_on_empty   = true
    placeholder_text = <span foreground="##cdc6b4">password...</span>
    hide_input      = false
    check_color     = rgb(ddc66e)
    fail_color      = rgb(ffb4ab)
    fail_text       = <i>wrong</i>
    capslock_color  = rgb(ddc66e)
    position        = 0, -80
    halign          = center
    valign          = center
}

# Ghost symbol
label {
    monitor     =
    text        = 󰊠
    color       = rgba(ddc66e99)
    font_size   = 42
    font_family = JetBrainsMono Nerd Font
    position    = 0, 310
    halign      = center
    valign      = center
}

# Clock
label {
    monitor     =
    text        = cmd[update:1000] echo "$(date +"%H:%M")"
    color       = rgba(e9e2d4ff)
    font_size   = 72
    font_family = JetBrains Mono Bold
    position    = 0, 200
    halign      = center
    valign      = center
}

# Date
label {
    monitor     =
    text        = cmd[update:60000] echo "$(date +"%A, %B %d")"
    color       = rgba(cdc6b4ff)
    font_size   = 18
    font_family = JetBrains Mono
    position    = 0, 120
    halign      = center
    valign      = center
}

# Username
label {
    monitor     =
    text        = gh0st
    color       = rgba(ddc66ebb)
    font_size   = 14
    font_family = JetBrains Mono Bold
    position    = 0, -30
    halign      = center
    valign      = center
}
