################
### MONITORS ###
################
# Layout: HDMI-A-1 (left) | DP-2 (center, main) | DP-3 (right) | DP-1 (TV, far right)
monitor = HDMI-A-1, 1920x1080@75,  0x0,    1
monitor = DP-2,     1920x1080@75,  1920x0, 1
monitor = DP-3,     1920x1080@60,  3840x0, 1
monitor = DP-1,     1920x1080@60,  5760x0, 1
monitor = ,         preferred,     auto,   1
