####################
### WINDOW RULES ###
####################
windowrule {
    name = suppress-maximize
    match:class = .*
    suppress_event = maximize
}

windowrule {
    name = float-pavucontrol
    match:class = ^(pavucontrol)$
    float = yes
}

windowrule {
    name = float-blueman
    match:class = ^(blueman-manager)$
    float = yes
}

windowrule {
    name = float-nm
    match:class = ^(nm-connection-editor)$
    float = yes
}

windowrule {
    name = float-pip
    match:title = ^(Picture-in-Picture)$
    float = yes
}

windowrule {
    name = float-dolphin
    match:class = ^(org.kde.dolphin)$
    float = yes
}

# nmtui floats as a compact network menu
windowrule {
    name = float-nmtui
    match:class = ^(nmtui-float)$
    float = yes
    size = 600 400
    center = yes
}

####################
### LAYER RULES  ###
####################
layerrule {
    name = blur-waybar
    match:namespace = waybar
    blur = true
}

layerrule {
    name = blur-rofi
    match:namespace = rofi
    blur = true
}

layerrule {
    name = blur-notifications
    match:namespace = notifications
    blur = true
}
