#!/home/gh0st/.local/share/pipx/venvs/black/bin/python
import sys
from black import patched_main
if __name__ == '__main__':
    sys.argv[0] = sys.argv[0].removesuffix('.exe')
    sys.exit(patched_main())
